name: Build remote branch
run-name: "Build remote branch: ${{ inputs.repo }}#${{ inputs.branch }}"

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository'
        required: true
      branch:
        description: 'Branch'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: |
          echo "Repository: ${{ inputs.repo }}"
          echo "Branch: ${{ inputs.branch }}"
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo }}
          token: ${{ secrets.RETE_QA_PUBLIC_PULL }}
          ref: ${{ inputs.branch }}
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Get npm package name
        id: package-info
        working-directory: dist
        run: |
          echo "::set-output name=name::$(node -p "require('./package.json').name")"
      - name: Print package info
        run: echo ${{ steps.package-info.outputs.name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package-info.outputs.name }}
          path: dist
