name: Daily Rete QA Regression

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'


jobs:
  run-tests:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        include:
          - stack: angular
            version: 17
            node: 18
          - stack: react
            version: 18
            node: 16
          - stack: vue
            version: 3
            node: 16
          - stack: svelte
            version: 4
            node: 16
    uses: ./.github/workflows/regression.yml
    with:
      name: ${{ matrix.stack }}
      version: ${{ matrix.version }}
      node: ${{ matrix.node }}
  
