name: Daily Rete QA Regression

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 */3 * *'

jobs:
  angular:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: [18,17,16,15,14,13,12]
    uses: ./.github/workflows/regression.yml
    with:
      name: angular
      version: ${{ matrix.version }}
      node: ${{ matrix.version < 14 && 14 || (matrix.version >=17 && 18 || 16) }}

  react:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        version: [18,17,16]
    uses: ./.github/workflows/regression.yml
    with:
      name: react-vite
      version: ${{ matrix.version }}
      node: 18

  vue:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        version: [3,2]
    uses: ./.github/workflows/regression.yml
    with:
      name: vue
      version: ${{ matrix.version }}
      node: 18

  svelte:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        version: [4,3]
    uses: ./.github/workflows/regression.yml
    with:
      name: svelte
      version: ${{ matrix.version }}
      node: 18

  lit:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        version: [3]
    uses: ./.github/workflows/regression.yml
    with:
      name: lit-vite
      version: ${{ matrix.version }}
      node: 20
