name: Rete QA Regression

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Stack
        options:
        - react
        - vue
        - angular
        - svelte
      version:
        type: number
        description: Stack version

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Install fonts
      run: |
        sudo apt-get -qqy update
        sudo apt-get -qqy --no-install-recommends install \
          libfontconfig \
          libfreetype6 \
          xfonts-cyrillic \
          xfonts-scalable \
          fonts-liberation \
          fonts-ipafont-gothic \
          fonts-wqy-zenhei \
          fonts-tlwg-loma-otf \
          fonts-freefont-ttf
        sudo rm -rf /var/lib/apt/lists/*
        sudo apt-get -qyy clean
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Build tool
      run: npm run build
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Init application
      run: node ./dist/index.js init -s ${{ github.event.inputs.name }} -sv ${{ github.event.inputs.version }}
      env:
        CI: ""
    - name: Run Playwright tests
      run: node ./dist/index.js test -s ${{ github.event.inputs.name }} -sv ${{ github.event.inputs.version }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 7
