name: Update all snaphots

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        default: main
      qa:
        description: 'Rete QA (<name>@<version> or <owner>/<repo>#<version>)'
        type: string
        default: 'rete-qa@latest'
      kit:
        description: 'Rete Kit (<name>@<version> or <owner>/<repo>#<version>)'
        type: string
        default: 'rete-kit@latest'


jobs:
  tools:
    name: Prepare tools
    uses: ./.github/workflows/prepare-qa-kit.yml
    secrets: inherit
    with:
      qa: ${{ inputs.qa }}
      kit: ${{ inputs.kit }}

  angular:
    needs: tools
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: [17,16,15,14,13,12]
    uses: ./.github/workflows/update-snapshots.yml
    secrets: inherit
    with:
      name: angular
      version: ${{ matrix.version }}
      node: ${{ matrix.version < 14 && 14 || (matrix.version >=17 && 18 || 16) }}
      branch: ${{ inputs.branch }}
      qa: ${{ needs.tools.outputs.qa-artifact }}
      kit: ${{ needs.tools.outputs.kit-artifact }}
      skip-tools: true
      qa-path: ${{ needs.tools.outputs.qa-path }}
      kit-path: ${{ needs.tools.outputs.kit-path }}

  react:
    needs: tools
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        version: [18,17,16]
    uses: ./.github/workflows/update-snapshots.yml
    secrets: inherit
    with:
      name: react
      version: ${{ matrix.version }}
      node: 18
      branch: ${{ inputs.branch }}
      qa: ${{ needs.tools.outputs.qa-artifact }}
      kit: ${{ needs.tools.outputs.kit-artifact }}
      skip-tools: true
      qa-path: ${{ needs.tools.outputs.qa-path }}
      kit-path: ${{ needs.tools.outputs.kit-path }}

  vue:
    needs: tools
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        version: [3,2]
    uses: ./.github/workflows/update-snapshots.yml
    secrets: inherit
    with:
      name: vue
      version: ${{ matrix.version }}
      node: 18
      branch: ${{ inputs.branch }}
      qa: ${{ needs.tools.outputs.qa-artifact }}
      kit: ${{ needs.tools.outputs.kit-artifact }}
      skip-tools: true
      qa-path: ${{ needs.tools.outputs.qa-path }}
      kit-path: ${{ needs.tools.outputs.kit-path }}

  svelte:
    needs: tools
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        version: [4,3]
    uses: ./.github/workflows/update-snapshots.yml
    secrets: inherit
    with:
      name: svelte
      version: ${{ matrix.version }}
      node: 18
      branch: ${{ inputs.branch }}
      qa: ${{ needs.tools.outputs.qa-artifact }}
      kit: ${{ needs.tools.outputs.kit-artifact }}
      skip-tools: true
      qa-path: ${{ needs.tools.outputs.qa-path }}
      kit-path: ${{ needs.tools.outputs.kit-path }}

  lit:
    needs: tools
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        version: [3]
    uses: ./.github/workflows/update-snapshots.yml
    secrets: inherit
    with:
      name: lit-vite
      version: ${{ matrix.version }}
      node: 20
      branch: ${{ inputs.branch }}
      qa: ${{ needs.tools.outputs.qa-artifact }}
      kit: ${{ needs.tools.outputs.kit-artifact }}
      skip-tools: true
      qa-path: ${{ needs.tools.outputs.qa-path }}
      kit-path: ${{ needs.tools.outputs.kit-path }}