name: Update snaphots
run-name: Update snaphots for ${{ inputs.name }} v${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: choice
        description: Stack
        options:
        - react
        - vue
        - angular
        - svelte
      version:
        required: true
        type: number
        description: Stack version
      node:
        type: number
        description: 'Node.js version (default: 16)'


jobs:
  update:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    # TODO reuse steps from regression.yml
    steps:
    - name: Install fonts
      run: |
        sudo apt-get -qqy update
        sudo apt-get -qqy --no-install-recommends install \
          libfontconfig \
          libfreetype6 \
          xfonts-cyrillic \
          xfonts-scalable \
          fonts-liberation \
          fonts-ipafont-gothic \
          fonts-wqy-zenhei \
          fonts-tlwg-loma-otf \
          fonts-freefont-ttf
        sudo rm -rf /var/lib/apt/lists/*
        sudo apt-get -qyy clean
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ github.event.inputs.node || 16 }}
    - name: Install Rete QA
      run: npm i -g rete-qa rete-kit
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Init application
      run: rete-qa init -s ${{ github.event.inputs.name }} -sv ${{ github.event.inputs.version }}
      env:
        CI: ""
    - name: Update snapshots
      run: rete-qa test -s ${{ github.event.inputs.name }} -sv ${{ github.event.inputs.version }} -u
    - name: Get path to snapshots
      id: get_snapshots
      run: echo "path=$(npm root -g)/rete-qa/snapshots/${{ github.event.inputs.name }}${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: snapshots
        path: ${{ steps.get_snapshots.outputs.path }}
        retention-days: 7
  
  send:
    runs-on: ubuntu-latest
    needs: update
    if: success('update')
    steps:
      # TODO reuse with update-docs.yml
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout rete-qa repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
          repository: retejs/rete-qa
      - name: Get path to snapshots
        id: snapshots_folder
        run: echo "path=./snapshots/${{ github.event.inputs.name }}${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          
      - name: Clear old snapshots
        run: rm -rf ${{ steps.snapshots_folder.path }}
        
      - uses: actions/download-artifact@v3
        with:
          name: snapshots
          path: ${{ steps.snapshots_folder.path }}
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate_token.outputs.token }}
          author: rete-js[bot] <rete-js[bot]@users.noreply.github.com>
          commit-message: "fix(snaphots): update snapshots for ${{ github.event.inputs.name }} v${{ github.event.inputs.version }}"
          title: Update snapshots for ${{ github.event.inputs.name }} v${{ github.event.inputs.version }}
          branch: update-snapshots-${{ github.event.inputs.name }}-v${{ github.event.inputs.version }}
          body: "Snapshots update for ${{ github.event.inputs.name }} v${{ github.event.inputs.version }}"
          reviewers: Ni55aN
    
    
